name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up a C++ compiler
      - name: Set up C++ Compiler
        run: sudo apt-get install -y g++ make

      # Step 3: Compile the code
      - name: Build
        run: |
          g++ -o main main.cpp

      # Step 4: Run the compiled program
      - name: Run the program
        run: ./main
